version: '2'

services:
  grafana:
    image: grafana/grafana-oss:latest
    hostname: grafana
    ports:
      - "3000:3000"
    volumes:
      - ~/Repos/PGC/volumes/grafana:/var/lib/grafana

  prometheus:
    image: prom/prometheus:v2.44.0
    hostname: prometheus
    command: ["--web.enable-remote-write-receiver", "--config.file=/etc/prometheus/prometheus.yml"]
    ports:
      - "9090:9090"
    volumes:
      - ./config:/etc/prometheus
      - ~/Repos/PGC/volumes/prometheus:/prometheus

  otel_collector:
    image: otel/opentelemetry-collector-contrib:latest
    hostname: otel_collector
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./config/otel-collector-config.yml:/etc/otel-collector-config.yaml
    ports:
      - "4318:4317"
      - "5555:5555"
      - "6666:6666"

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    hostname: tempo
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml
      - ~/Repos/PGC/volumes/tempo:/tmp/tempo
    ports:
      - "3200:3200"
      - "4317:4317"

  loki:
    image: grafana/loki:latest
    hostname: loki
    command: [ "-config.file=/mnt/config/loki-config.yaml" ]
    volumes:
      - ./config/loki-config.yaml:/mnt/config/loki-config.yaml
      - ~/Repos/PGC/volumes/loki:/var/lib/grafana
    ports:
      - "3100:3100"

  # api:
  #   image: dice
  #   hostname: dice-api
  #   depends_on: 
  #     - postgres
  #   ports:
  #     - "5001:5001"
  #     - "8000:8000"
  #   environment:
  #     - OTEL_PYTHON_LOG_CORRELATION=true
  #     - OTEL_PYTHON_LOG_LEVEL=DEBUG
  #     - OTEL_PYTHON_LOG_FORMAT=json
  #     - RUNNING_ON_CONTAINER=true
  
  email-api:
    image: email:v2.0.0
    hostname: email-api
    depends_on: 
      postgres:
        condition: service_healthy
    ports:
      - "5002:5001"
      - "8001:8000"
    environment:
      - ENV=development
      - DATABASE_HOST=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=dice
      - COLLECTOR_URL=otel_collector:4317
      - PROMETHEUS_PORT=8000
      - PORT=5001
      - SMTP_SENDER=migueldreis01@gmail.com
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_PASSWORD=evcrjetkkolkzjdu
      - AUTH_EXPIRATION=172800
      - AUTH_SECRET=wn9AmoDNnqGSHi38poXA
      - AUTH_ADMIN_KEY=5JU3dD4AJuKXGRpAgVKe

  postgres:
    image: postgres:latest
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dice
    volumes:
      - ~/Repos/PGC/volumes/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "myuser"]
      interval: 10s
      timeout: 5s
      retries: 5