version: '2'

services:
  grafana:
    image: grafana/grafana-oss:latest
    hostname: grafana
    ports:
      - "3000:3000"
    volumes:
      - ~/Documents/Repos/ufabc/pgc/Volumes/grafana:/var/lib/grafana

  prometheus:
    image: prom/prometheus:latest
    hostname: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config:/etc/prometheus
      - ~/Documents/Repos/ufabc/pgc/Volumes/prometheus:/prometheus

  otel_collector:
    image: otel/opentelemetry-collector-contrib:latest
    hostname: otel_collector
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./configs/otel_config/otel-collector-config.yml:/etc/otel-collector-config.yaml
    ports:
      - "4318:4317"
      - "5555:5555"
      - "6666:6666"

  tempo:
    image: grafana/tempo:latest
    command: [ "-search.enabled=true", "-config.file=/etc/tempo.yaml" ]
    hostname: tempo
    volumes:
      - ./configs/tempo_config/tempo.yaml:/etc/tempo.yaml
      - ./configs/tempo_config/overrides.yaml:/etc/overrides.yaml
      - ./tempo_data:/tmp/tempo
    ports:
      - "3200:3200"
      - "4317:4317"

  loki:
    image: grafana/loki:latest
    hostname: loki
    command: ["-config.file=/mnt/config/loki-config.yaml"]
    volumes:
      - ./configs/loki_config/loki-config.yaml:/mnt/config/loki-config.yaml
    ports:
      - "3100:3100"

  api:
    image: dice
    hostname: dice-api
    ports:
      - "5001:5000"
      - "8000:8000"
    environment:
      - OTEL_PYTHON_LOG_CORRELATION=true
      - OTEL_PYTHON_LOG_FORMAT=true