# /otel_config/otel-collector-config.yml
receivers:
  otlp:
    protocols:
      grpc:
      http:
  filelog:
    include: ["/var/log/*.log"]
  prometheus:
    config:
      scrape_configs:
        - job_name: "otel-collector"
          scrape_interval: 15s
          static_configs:
            - targets: ["localhost:8888"] # otel-collector metrics port

processors:
  batch:
  attributes:
    actions:
      - action: insert
        key: loki.attribute.labels
        value: log.file.name

exporters:
  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write
  otlp:
    endpoint: http://tempo:4317
    tls:
      insecure: true
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    logs:
      receivers: [otlp, filelog]
      processors: [attributes, batch]
      exporters: [loki]
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [prometheusremotewrite]