server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        http:
    
storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/blocks
    pool:
      max_workers: 100
      queue_depth: 10000
